# Generated by Django 5.1.7 on 2025-03-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updatedOn',
            new_name='updated_on',
        ),
    ]
