# Generated by Django 5.2 on 2025-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
