# Generated by Django 5.1.7 on 2025-03-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on'], 'verbose_name': 'Commission', 'verbose_name_plural': 'Commissions'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updatedOn',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='peopleRequired',
            new_name='people_required',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='updatedOn',
            new_name='updated_on',
        ),
    ]
